#ifndef IOLITE_INPUT_DEFINES_H
#define IOLITE_INPUT_DEFINES_H

#include "iol_definitions.h"

#define IOLK_SCANCODE_MASK (1<<30)
#define IOL_SCANCODE_TO_KEYCODE(X)  (X | IOLK_SCANCODE_MASK)

enum KeyState
{
	KeyState_None,
	KeyState_Pressed,
	KeyState_Released,
	KeyState_Holding,

	KeyState_Count
};

enum MouseButton
{
	MouseButton_None,
	MouseButton_Left,
	MouseButton_Middle,
	MouseButton_Right,
	MouseButton_X1,
	MouseButton_X2,

	MouseButton_Count
};

enum ScanCode
{
	IOL_SCANCODE_UNKNOWN = 0,

	/**
	 *  \name Usage page 0x07
	 *
	 *  These values are from usage page 0x07 (USB keyboard page).
	 */
	 /* @{ */

	 IOL_SCANCODE_A = 4,
	 IOL_SCANCODE_B = 5,
	 IOL_SCANCODE_C = 6,
	 IOL_SCANCODE_D = 7,
	 IOL_SCANCODE_E = 8,
	 IOL_SCANCODE_F = 9,
	 IOL_SCANCODE_G = 10,
	 IOL_SCANCODE_H = 11,
	 IOL_SCANCODE_I = 12,
	 IOL_SCANCODE_J = 13,
	 IOL_SCANCODE_K = 14,
	 IOL_SCANCODE_L = 15,
	 IOL_SCANCODE_M = 16,
	 IOL_SCANCODE_N = 17,
	 IOL_SCANCODE_O = 18,
	 IOL_SCANCODE_P = 19,
	 IOL_SCANCODE_Q = 20,
	 IOL_SCANCODE_R = 21,
	 IOL_SCANCODE_S = 22,
	 IOL_SCANCODE_T = 23,
	 IOL_SCANCODE_U = 24,
	 IOL_SCANCODE_V = 25,
	 IOL_SCANCODE_W = 26,
	 IOL_SCANCODE_X = 27,
	 IOL_SCANCODE_Y = 28,
	 IOL_SCANCODE_Z = 29,

	 IOL_SCANCODE_1 = 30,
	 IOL_SCANCODE_2 = 31,
	 IOL_SCANCODE_3 = 32,
	 IOL_SCANCODE_4 = 33,
	 IOL_SCANCODE_5 = 34,
	 IOL_SCANCODE_6 = 35,
	 IOL_SCANCODE_7 = 36,
	 IOL_SCANCODE_8 = 37,
	 IOL_SCANCODE_9 = 38,
	 IOL_SCANCODE_0 = 39,

	 IOL_SCANCODE_RETURN = 40,
	 IOL_SCANCODE_ESCAPE = 41,
	 IOL_SCANCODE_BACKSPACE = 42,
	 IOL_SCANCODE_TAB = 43,
	 IOL_SCANCODE_SPACE = 44,

	 IOL_SCANCODE_MINUS = 45,
	 IOL_SCANCODE_EQUALS = 46,
	 IOL_SCANCODE_LEFTBRACKET = 47,
	 IOL_SCANCODE_RIGHTBRACKET = 48,
	 IOL_SCANCODE_BACKSLASH = 49, /**< Located at the lower left of the return
								   *   key on ISO keyboards and at the right end
								   *   of the QWERTY row on ANSI keyboards.
								   *   Produces REVERSE SOLIDUS (backslash) and
								   *   VERTICAL LINE in a US layout, REVERSE
								   *   SOLIDUS and VERTICAL LINE in a UK Mac
								   *   layout, NUMBER SIGN and TILDE in a UK
								   *   Windows layout, DOLLAR SIGN and POUND SIGN
								   *   in a Swiss German layout, NUMBER SIGN and
								   *   APOSTROPHE in a German layout, GRAVE
								   *   ACCENT and POUND SIGN in a French Mac
								   *   layout, and ASTERISK and MICRO SIGN in a
								   *   French Windows layout.
								   */
	IOL_SCANCODE_NONUSHASH = 50, /**< ISO USB keyboards actually use this code
								  *   instead of 49 for the same key, but all
								  *   OSes I've seen treat the two codes
								  *   identically. So, as an implementor, unless
								  *   your keyboard generates both of those
								  *   codes and your OS treats them differently,
								  *   you should generate IOL_SCANCODE_BACKSLASH
								  *   instead of this code. As a user, you
								  *   should not rely on this code because SDL
								  *   will never generate it with most (all?)
								  *   keyboards.
								  */
	IOL_SCANCODE_SEMICOLON = 51,
	IOL_SCANCODE_APOSTROPHE = 52,
	IOL_SCANCODE_GRAVE = 53, /**< Located in the top left corner (on both ANSI
							  *   and ISO keyboards). Produces GRAVE ACCENT and
							  *   TILDE in a US Windows layout and in US and UK
							  *   Mac layouts on ANSI keyboards, GRAVE ACCENT
							  *   and NOT SIGN in a UK Windows layout, SECTION
							  *   SIGN and PLUS-MINUS SIGN in US and UK Mac
							  *   layouts on ISO keyboards, SECTION SIGN and
							  *   DEGREE SIGN in a Swiss German layout (Mac:
							  *   only on ISO keyboards), CIRCUMFLEX ACCENT and
							  *   DEGREE SIGN in a German layout (Mac: only on
							  *   ISO keyboards), SUPERSCRIPT TWO and TILDE in a
							  *   French Windows layout, COMMERCIAL AT and
							  *   NUMBER SIGN in a French Mac layout on ISO
							  *   keyboards, and LESS-THAN SIGN and GREATER-THAN
							  *   SIGN in a Swiss German, German, or French Mac
							  *   layout on ANSI keyboards.
							  */
	IOL_SCANCODE_COMMA = 54,
	IOL_SCANCODE_PERIOD = 55,
	IOL_SCANCODE_SLASH = 56,

	IOL_SCANCODE_CAPSLOCK = 57,

	IOL_SCANCODE_F1 = 58,
	IOL_SCANCODE_F2 = 59,
	IOL_SCANCODE_F3 = 60,
	IOL_SCANCODE_F4 = 61,
	IOL_SCANCODE_F5 = 62,
	IOL_SCANCODE_F6 = 63,
	IOL_SCANCODE_F7 = 64,
	IOL_SCANCODE_F8 = 65,
	IOL_SCANCODE_F9 = 66,
	IOL_SCANCODE_F10 = 67,
	IOL_SCANCODE_F11 = 68,
	IOL_SCANCODE_F12 = 69,

	IOL_SCANCODE_PRINTSCREEN = 70,
	IOL_SCANCODE_SCROLLLOCK = 71,
	IOL_SCANCODE_PAUSE = 72,
	IOL_SCANCODE_INSERT = 73, /**< insert on PC, help on some Mac keyboards (but
								   does send code 73, not 117) */
	IOL_SCANCODE_HOME = 74,
	IOL_SCANCODE_PAGEUP = 75,
	IOL_SCANCODE_DELETE = 76,
	IOL_SCANCODE_END = 77,
	IOL_SCANCODE_PAGEDOWN = 78,
	IOL_SCANCODE_RIGHT = 79,
	IOL_SCANCODE_LEFT = 80,
	IOL_SCANCODE_DOWN = 81,
	IOL_SCANCODE_UP = 82,

	IOL_SCANCODE_NUMLOCKCLEAR = 83, /**< num lock on PC, clear on Mac keyboards
									 */
	IOL_SCANCODE_KP_DIVIDE = 84,
	IOL_SCANCODE_KP_MULTIPLY = 85,
	IOL_SCANCODE_KP_MINUS = 86,
	IOL_SCANCODE_KP_PLUS = 87,
	IOL_SCANCODE_KP_ENTER = 88,
	IOL_SCANCODE_KP_1 = 89,
	IOL_SCANCODE_KP_2 = 90,
	IOL_SCANCODE_KP_3 = 91,
	IOL_SCANCODE_KP_4 = 92,
	IOL_SCANCODE_KP_5 = 93,
	IOL_SCANCODE_KP_6 = 94,
	IOL_SCANCODE_KP_7 = 95,
	IOL_SCANCODE_KP_8 = 96,
	IOL_SCANCODE_KP_9 = 97,
	IOL_SCANCODE_KP_0 = 98,
	IOL_SCANCODE_KP_PERIOD = 99,

	IOL_SCANCODE_NONUSBACKSLASH = 100, /**< This is the additional key that ISO
										*   keyboards have over ANSI ones,
										*   located between left shift and Y.
										*   Produces GRAVE ACCENT and TILDE in a
										*   US or UK Mac layout, REVERSE SOLIDUS
										*   (backslash) and VERTICAL LINE in a
										*   US or UK Windows layout, and
										*   LESS-THAN SIGN and GREATER-THAN SIGN
										*   in a Swiss German, German, or French
										*   layout. */
	IOL_SCANCODE_APPLICATION = 101, /**< windows contextual menu, compose */
	IOL_SCANCODE_POWER = 102, /**< The USB document says this is a status flag,
							   *   not a physical key - but some Mac keyboards
							   *   do have a power key. */
	IOL_SCANCODE_KP_EQUALS = 103,
	IOL_SCANCODE_F13 = 104,
	IOL_SCANCODE_F14 = 105,
	IOL_SCANCODE_F15 = 106,
	IOL_SCANCODE_F16 = 107,
	IOL_SCANCODE_F17 = 108,
	IOL_SCANCODE_F18 = 109,
	IOL_SCANCODE_F19 = 110,
	IOL_SCANCODE_F20 = 111,
	IOL_SCANCODE_F21 = 112,
	IOL_SCANCODE_F22 = 113,
	IOL_SCANCODE_F23 = 114,
	IOL_SCANCODE_F24 = 115,
	IOL_SCANCODE_EXECUTE = 116,
	IOL_SCANCODE_HELP = 117,
	IOL_SCANCODE_MENU = 118,
	IOL_SCANCODE_SELECT = 119,
	IOL_SCANCODE_STOP = 120,
	IOL_SCANCODE_AGAIN = 121,   /**< redo */
	IOL_SCANCODE_UNDO = 122,
	IOL_SCANCODE_CUT = 123,
	IOL_SCANCODE_COPY = 124,
	IOL_SCANCODE_PASTE = 125,
	IOL_SCANCODE_FIND = 126,
	IOL_SCANCODE_MUTE = 127,
	IOL_SCANCODE_VOLUMEUP = 128,
	IOL_SCANCODE_VOLUMEDOWN = 129,
	/* not sure whether there's a reason to enable these */
	/*     IOL_SCANCODE_LOCKINGCAPSLOCK = 130,  */
	/*     IOL_SCANCODE_LOCKINGNUMLOCK = 131, */
	/*     IOL_SCANCODE_LOCKINGSCROLLLOCK = 132, */
	IOL_SCANCODE_KP_COMMA = 133,
	IOL_SCANCODE_KP_EQUALSAS400 = 134,

	IOL_SCANCODE_INTERNATIONAL1 = 135, /**< used on Asian keyboards, see
											footnotes in USB doc */
	IOL_SCANCODE_INTERNATIONAL2 = 136,
	IOL_SCANCODE_INTERNATIONAL3 = 137, /**< Yen */
	IOL_SCANCODE_INTERNATIONAL4 = 138,
	IOL_SCANCODE_INTERNATIONAL5 = 139,
	IOL_SCANCODE_INTERNATIONAL6 = 140,
	IOL_SCANCODE_INTERNATIONAL7 = 141,
	IOL_SCANCODE_INTERNATIONAL8 = 142,
	IOL_SCANCODE_INTERNATIONAL9 = 143,
	IOL_SCANCODE_LANG1 = 144, /**< Hangul/English toggle */
	IOL_SCANCODE_LANG2 = 145, /**< Hanja conversion */
	IOL_SCANCODE_LANG3 = 146, /**< Katakana */
	IOL_SCANCODE_LANG4 = 147, /**< Hiragana */
	IOL_SCANCODE_LANG5 = 148, /**< Zenkaku/Hankaku */
	IOL_SCANCODE_LANG6 = 149, /**< reserved */
	IOL_SCANCODE_LANG7 = 150, /**< reserved */
	IOL_SCANCODE_LANG8 = 151, /**< reserved */
	IOL_SCANCODE_LANG9 = 152, /**< reserved */

	IOL_SCANCODE_ALTERASE = 153, /**< Erase-Eaze */
	IOL_SCANCODE_SYSREQ = 154,
	IOL_SCANCODE_CANCEL = 155,
	IOL_SCANCODE_CLEAR = 156,
	IOL_SCANCODE_PRIOR = 157,
	IOL_SCANCODE_RETURN2 = 158,
	IOL_SCANCODE_SEPARATOR = 159,
	IOL_SCANCODE_OUT = 160,
	IOL_SCANCODE_OPER = 161,
	IOL_SCANCODE_CLEARAGAIN = 162,
	IOL_SCANCODE_CRSEL = 163,
	IOL_SCANCODE_EXSEL = 164,

	IOL_SCANCODE_KP_00 = 176,
	IOL_SCANCODE_KP_000 = 177,
	IOL_SCANCODE_THOUSANDSSEPARATOR = 178,
	IOL_SCANCODE_DECIMALSEPARATOR = 179,
	IOL_SCANCODE_CURRENCYUNIT = 180,
	IOL_SCANCODE_CURRENCYSUBUNIT = 181,
	IOL_SCANCODE_KP_LEFTPAREN = 182,
	IOL_SCANCODE_KP_RIGHTPAREN = 183,
	IOL_SCANCODE_KP_LEFTBRACE = 184,
	IOL_SCANCODE_KP_RIGHTBRACE = 185,
	IOL_SCANCODE_KP_TAB = 186,
	IOL_SCANCODE_KP_BACKSPACE = 187,
	IOL_SCANCODE_KP_A = 188,
	IOL_SCANCODE_KP_B = 189,
	IOL_SCANCODE_KP_C = 190,
	IOL_SCANCODE_KP_D = 191,
	IOL_SCANCODE_KP_E = 192,
	IOL_SCANCODE_KP_F = 193,
	IOL_SCANCODE_KP_XOR = 194,
	IOL_SCANCODE_KP_POWER = 195,
	IOL_SCANCODE_KP_PERCENT = 196,
	IOL_SCANCODE_KP_LESS = 197,
	IOL_SCANCODE_KP_GREATER = 198,
	IOL_SCANCODE_KP_AMPERSAND = 199,
	IOL_SCANCODE_KP_DBLAMPERSAND = 200,
	IOL_SCANCODE_KP_VERTICALBAR = 201,
	IOL_SCANCODE_KP_DBLVERTICALBAR = 202,
	IOL_SCANCODE_KP_COLON = 203,
	IOL_SCANCODE_KP_HASH = 204,
	IOL_SCANCODE_KP_SPACE = 205,
	IOL_SCANCODE_KP_AT = 206,
	IOL_SCANCODE_KP_EXCLAM = 207,
	IOL_SCANCODE_KP_MEMSTORE = 208,
	IOL_SCANCODE_KP_MEMRECALL = 209,
	IOL_SCANCODE_KP_MEMCLEAR = 210,
	IOL_SCANCODE_KP_MEMADD = 211,
	IOL_SCANCODE_KP_MEMSUBTRACT = 212,
	IOL_SCANCODE_KP_MEMMULTIPLY = 213,
	IOL_SCANCODE_KP_MEMDIVIDE = 214,
	IOL_SCANCODE_KP_PLUSMINUS = 215,
	IOL_SCANCODE_KP_CLEAR = 216,
	IOL_SCANCODE_KP_CLEARENTRY = 217,
	IOL_SCANCODE_KP_BINARY = 218,
	IOL_SCANCODE_KP_OCTAL = 219,
	IOL_SCANCODE_KP_DECIMAL = 220,
	IOL_SCANCODE_KP_HEXADECIMAL = 221,

	IOL_SCANCODE_LCTRL = 224,
	IOL_SCANCODE_LSHIFT = 225,
	IOL_SCANCODE_LALT = 226, /**< alt, option */
	IOL_SCANCODE_LGUI = 227, /**< windows, command (apple), meta */
	IOL_SCANCODE_RCTRL = 228,
	IOL_SCANCODE_RSHIFT = 229,
	IOL_SCANCODE_RALT = 230, /**< alt gr, option */
	IOL_SCANCODE_RGUI = 231, /**< windows, command (apple), meta */

	IOL_SCANCODE_MODE = 257,    /**< I'm not sure if this is really not covered
								 *   by any of the above, but since there's a
								 *   special KMOD_MODE for it I'm adding it here
								 */

	/* @} *//* Usage page 0x07 */

	/**
	*  \name Usage page 0x0C
	*
	*  These values are mapped from usage page 0x0C (USB consumer page).
	*/
	/* @{ */

	IOL_SCANCODE_AUDIONEXT = 258,
	IOL_SCANCODE_AUDIOPREV = 259,
	IOL_SCANCODE_AUDIOSTOP = 260,
	IOL_SCANCODE_AUDIOPLAY = 261,
	IOL_SCANCODE_AUDIOMUTE = 262,
	IOL_SCANCODE_MEDIASELECT = 263,
	IOL_SCANCODE_WWW = 264,
	IOL_SCANCODE_MAIL = 265,
	IOL_SCANCODE_CALCULATOR = 266,
	IOL_SCANCODE_COMPUTER = 267,
	IOL_SCANCODE_AC_SEARCH = 268,
	IOL_SCANCODE_AC_HOME = 269,
	IOL_SCANCODE_AC_BACK = 270,
	IOL_SCANCODE_AC_FORWARD = 271,
	IOL_SCANCODE_AC_STOP = 272,
	IOL_SCANCODE_AC_REFRESH = 273,
	IOL_SCANCODE_AC_BOOKMARKS = 274,

	/* @} *//* Usage page 0x0C */

	/**
	*  \name Walther keys
	*
	*  These are values that Christian Walther added (for mac keyboard?).
	*/
	/* @{ */

	IOL_SCANCODE_BRIGHTNESSDOWN = 275,
	IOL_SCANCODE_BRIGHTNESSUP = 276,
	IOL_SCANCODE_DISPLAYSWITCH = 277, /**< display mirroring/dual display
											switch, video mode switch */
	IOL_SCANCODE_KBDILLUMTOGGLE = 278,
	IOL_SCANCODE_KBDILLUMDOWN = 279,
	IOL_SCANCODE_KBDILLUMUP = 280,
	IOL_SCANCODE_EJECT = 281,
	IOL_SCANCODE_SLEEP = 282,

	IOL_SCANCODE_APP1 = 283,
	IOL_SCANCODE_APP2 = 284,

	/* @} *//* Walther keys */

	/**
	 *  \name Usage page 0x0C (additional media keys)
	 *
	 *  These values are mapped from usage page 0x0C (USB consumer page).
	 */
	 /* @{ */

	 IOL_SCANCODE_AUDIOREWIND = 285,
	 IOL_SCANCODE_AUDIOFASTFORWARD = 286,

	 /* @} *//* Usage page 0x0C (additional media keys) */

	 /* Add any other keys here. */

	 IOL_NUM_SCANCODES = 512 /**< not a key, just marks the number of scancodes
								  for array bounds */
};

typedef int32 KeyCode;

enum
{
	IOLK_UNKNOWN = 0,

	IOLK_RETURN = '\r',
	IOLK_ESCAPE = '\033',
	IOLK_BACKSPACE = '\b',
	IOLK_TAB = '\t',
	IOLK_SPACE = ' ',
	IOLK_EXCLAIM = '!',
	IOLK_QUOTEDBL = '"',
	IOLK_HASH = '#',
	IOLK_PERCENT = '%',
	IOLK_DOLLAR = '$',
	IOLK_AMPERSAND = '&',
	IOLK_QUOTE = '\'',
	IOLK_LEFTPAREN = '(',
	IOLK_RIGHTPAREN = ')',
	IOLK_ASTERISK = '*',
	IOLK_PLUS = '+',
	IOLK_COMMA = ',',
	IOLK_MINUS = '-',
	IOLK_PERIOD = '.',
	IOLK_SLASH = '/',
	IOLK_0 = '0',
	IOLK_1 = '1',
	IOLK_2 = '2',
	IOLK_3 = '3',
	IOLK_4 = '4',
	IOLK_5 = '5',
	IOLK_6 = '6',
	IOLK_7 = '7',
	IOLK_8 = '8',
	IOLK_9 = '9',
	IOLK_COLON = ':',
	IOLK_SEMICOLON = ';',
	IOLK_LESS = '<',
	IOLK_EQUALS = '=',
	IOLK_GREATER = '>',
	IOLK_QUESTION = '?',
	IOLK_AT = '@',
	/*
	   Skip uppercase letters
	 */
	IOLK_LEFTBRACKET = '[',
	IOLK_BACKSLASH = '\\',
	IOLK_RIGHTBRACKET = ']',
	IOLK_CARET = '^',
	IOLK_UNDERSCORE = '_',
	IOLK_BACKQUOTE = '`',
	IOLK_a = 'a',
	IOLK_b = 'b',
	IOLK_c = 'c',
	IOLK_d = 'd',
	IOLK_e = 'e',
	IOLK_f = 'f',
	IOLK_g = 'g',
	IOLK_h = 'h',
	IOLK_i = 'i',
	IOLK_j = 'j',
	IOLK_k = 'k',
	IOLK_l = 'l',
	IOLK_m = 'm',
	IOLK_n = 'n',
	IOLK_o = 'o',
	IOLK_p = 'p',
	IOLK_q = 'q',
	IOLK_r = 'r',
	IOLK_s = 's',
	IOLK_t = 't',
	IOLK_u = 'u',
	IOLK_v = 'v',
	IOLK_w = 'w',
	IOLK_x = 'x',
	IOLK_y = 'y',
	IOLK_z = 'z',

	IOLK_CAPSLOCK = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_CAPSLOCK),

	IOLK_F1 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_F1),
	IOLK_F2 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_F2),
	IOLK_F3 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_F3),
	IOLK_F4 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_F4),
	IOLK_F5 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_F5),
	IOLK_F6 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_F6),
	IOLK_F7 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_F7),
	IOLK_F8 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_F8),
	IOLK_F9 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_F9),
	IOLK_F10 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_F10),
	IOLK_F11 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_F11),
	IOLK_F12 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_F12),

	IOLK_PRINTSCREEN = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_PRINTSCREEN),
	IOLK_SCROLLLOCK = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_SCROLLLOCK),
	IOLK_PAUSE = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_PAUSE),
	IOLK_INSERT = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_INSERT),
	IOLK_HOME = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_HOME),
	IOLK_PAGEUP = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_PAGEUP),
	IOLK_DELETE = '\177',
	IOLK_END = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_END),
	IOLK_PAGEDOWN = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_PAGEDOWN),
	IOLK_RIGHT = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_RIGHT),
	IOLK_LEFT = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_LEFT),
	IOLK_DOWN = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_DOWN),
	IOLK_UP = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_UP),

	IOLK_NUMLOCKCLEAR = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_NUMLOCKCLEAR),
	IOLK_KP_DIVIDE = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_DIVIDE),
	IOLK_KP_MULTIPLY = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_MULTIPLY),
	IOLK_KP_MINUS = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_MINUS),
	IOLK_KP_PLUS = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_PLUS),
	IOLK_KP_ENTER = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_ENTER),
	IOLK_KP_1 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_1),
	IOLK_KP_2 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_2),
	IOLK_KP_3 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_3),
	IOLK_KP_4 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_4),
	IOLK_KP_5 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_5),
	IOLK_KP_6 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_6),
	IOLK_KP_7 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_7),
	IOLK_KP_8 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_8),
	IOLK_KP_9 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_9),
	IOLK_KP_0 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_0),
	IOLK_KP_PERIOD = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_PERIOD),

	IOLK_APPLICATION = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_APPLICATION),
	IOLK_POWER = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_POWER),
	IOLK_KP_EQUALS = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_EQUALS),
	IOLK_F13 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_F13),
	IOLK_F14 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_F14),
	IOLK_F15 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_F15),
	IOLK_F16 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_F16),
	IOLK_F17 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_F17),
	IOLK_F18 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_F18),
	IOLK_F19 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_F19),
	IOLK_F20 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_F20),
	IOLK_F21 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_F21),
	IOLK_F22 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_F22),
	IOLK_F23 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_F23),
	IOLK_F24 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_F24),
	IOLK_EXECUTE = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_EXECUTE),
	IOLK_HELP = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_HELP),
	IOLK_MENU = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_MENU),
	IOLK_SELECT = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_SELECT),
	IOLK_STOP = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_STOP),
	IOLK_AGAIN = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_AGAIN),
	IOLK_UNDO = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_UNDO),
	IOLK_CUT = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_CUT),
	IOLK_COPY = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_COPY),
	IOLK_PASTE = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_PASTE),
	IOLK_FIND = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_FIND),
	IOLK_MUTE = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_MUTE),
	IOLK_VOLUMEUP = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_VOLUMEUP),
	IOLK_VOLUMEDOWN = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_VOLUMEDOWN),
	IOLK_KP_COMMA = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_COMMA),
	IOLK_KP_EQUALSAS400 =
	IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_EQUALSAS400),

	IOLK_ALTERASE = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_ALTERASE),
	IOLK_SYSREQ = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_SYSREQ),
	IOLK_CANCEL = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_CANCEL),
	IOLK_CLEAR = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_CLEAR),
	IOLK_PRIOR = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_PRIOR),
	IOLK_RETURN2 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_RETURN2),
	IOLK_SEPARATOR = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_SEPARATOR),
	IOLK_OUT = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_OUT),
	IOLK_OPER = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_OPER),
	IOLK_CLEARAGAIN = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_CLEARAGAIN),
	IOLK_CRSEL = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_CRSEL),
	IOLK_EXSEL = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_EXSEL),

	IOLK_KP_00 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_00),
	IOLK_KP_000 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_000),
	IOLK_THOUSANDSSEPARATOR =
	IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_THOUSANDSSEPARATOR),
	IOLK_DECIMALSEPARATOR =
	IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_DECIMALSEPARATOR),
	IOLK_CURRENCYUNIT = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_CURRENCYUNIT),
	IOLK_CURRENCYSUBUNIT =
	IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_CURRENCYSUBUNIT),
	IOLK_KP_LEFTPAREN = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_LEFTPAREN),
	IOLK_KP_RIGHTPAREN = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_RIGHTPAREN),
	IOLK_KP_LEFTBRACE = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_LEFTBRACE),
	IOLK_KP_RIGHTBRACE = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_RIGHTBRACE),
	IOLK_KP_TAB = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_TAB),
	IOLK_KP_BACKSPACE = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_BACKSPACE),
	IOLK_KP_A = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_A),
	IOLK_KP_B = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_B),
	IOLK_KP_C = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_C),
	IOLK_KP_D = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_D),
	IOLK_KP_E = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_E),
	IOLK_KP_F = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_F),
	IOLK_KP_XOR = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_XOR),
	IOLK_KP_POWER = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_POWER),
	IOLK_KP_PERCENT = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_PERCENT),
	IOLK_KP_LESS = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_LESS),
	IOLK_KP_GREATER = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_GREATER),
	IOLK_KP_AMPERSAND = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_AMPERSAND),
	IOLK_KP_DBLAMPERSAND =
	IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_DBLAMPERSAND),
	IOLK_KP_VERTICALBAR =
	IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_VERTICALBAR),
	IOLK_KP_DBLVERTICALBAR =
	IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_DBLVERTICALBAR),
	IOLK_KP_COLON = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_COLON),
	IOLK_KP_HASH = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_HASH),
	IOLK_KP_SPACE = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_SPACE),
	IOLK_KP_AT = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_AT),
	IOLK_KP_EXCLAM = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_EXCLAM),
	IOLK_KP_MEMSTORE = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_MEMSTORE),
	IOLK_KP_MEMRECALL = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_MEMRECALL),
	IOLK_KP_MEMCLEAR = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_MEMCLEAR),
	IOLK_KP_MEMADD = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_MEMADD),
	IOLK_KP_MEMSUBTRACT =
	IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_MEMSUBTRACT),
	IOLK_KP_MEMMULTIPLY =
	IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_MEMMULTIPLY),
	IOLK_KP_MEMDIVIDE = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_MEMDIVIDE),
	IOLK_KP_PLUSMINUS = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_PLUSMINUS),
	IOLK_KP_CLEAR = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_CLEAR),
	IOLK_KP_CLEARENTRY = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_CLEARENTRY),
	IOLK_KP_BINARY = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_BINARY),
	IOLK_KP_OCTAL = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_OCTAL),
	IOLK_KP_DECIMAL = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_DECIMAL),
	IOLK_KP_HEXADECIMAL =
	IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KP_HEXADECIMAL),

	IOLK_LCTRL = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_LCTRL),
	IOLK_LSHIFT = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_LSHIFT),
	IOLK_LALT = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_LALT),
	IOLK_LGUI = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_LGUI),
	IOLK_RCTRL = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_RCTRL),
	IOLK_RSHIFT = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_RSHIFT),
	IOLK_RALT = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_RALT),
	IOLK_RGUI = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_RGUI),

	IOLK_MODE = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_MODE),

	IOLK_AUDIONEXT = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_AUDIONEXT),
	IOLK_AUDIOPREV = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_AUDIOPREV),
	IOLK_AUDIOSTOP = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_AUDIOSTOP),
	IOLK_AUDIOPLAY = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_AUDIOPLAY),
	IOLK_AUDIOMUTE = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_AUDIOMUTE),
	IOLK_MEDIASELECT = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_MEDIASELECT),
	IOLK_WWW = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_WWW),
	IOLK_MAIL = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_MAIL),
	IOLK_CALCULATOR = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_CALCULATOR),
	IOLK_COMPUTER = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_COMPUTER),
	IOLK_AC_SEARCH = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_AC_SEARCH),
	IOLK_AC_HOME = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_AC_HOME),
	IOLK_AC_BACK = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_AC_BACK),
	IOLK_AC_FORWARD = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_AC_FORWARD),
	IOLK_AC_STOP = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_AC_STOP),
	IOLK_AC_REFRESH = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_AC_REFRESH),
	IOLK_AC_BOOKMARKS = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_AC_BOOKMARKS),

	IOLK_BRIGHTNESSDOWN =
	IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_BRIGHTNESSDOWN),
	IOLK_BRIGHTNESSUP = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_BRIGHTNESSUP),
	IOLK_DISPLAYSWITCH = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_DISPLAYSWITCH),
	IOLK_KBDILLUMTOGGLE =
	IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KBDILLUMTOGGLE),
	IOLK_KBDILLUMDOWN = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KBDILLUMDOWN),
	IOLK_KBDILLUMUP = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_KBDILLUMUP),
	IOLK_EJECT = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_EJECT),
	IOLK_SLEEP = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_SLEEP),
	IOLK_APP1 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_APP1),
	IOLK_APP2 = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_APP2),

	IOLK_AUDIOREWIND = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_AUDIOREWIND),
	IOLK_AUDIOFASTFORWARD = IOL_SCANCODE_TO_KEYCODE(IOL_SCANCODE_AUDIOFASTFORWARD)
};

#endif // IOLITE_INPUT_DEFINES_H